### ISSUE TITLE
Problem with redis

### ISSUE THREAD

**Issue by Sethlans** [yagop/telegram-bot#138]
When i run the bot it starts normally but it doesn't execute any command
This error show up when i start the bot
lua: ./bot/bot.lua:234: attempt to call a nil value
the following error show everytime i launch a command
 *** lua: plugins/stats.lua:73: attempt to index global 'redis' (a nil value)

**Comment by rockneurotiko** [comment]
Since 4 or 5 days ago @yagop added redis as a dependency, and some plugins use it (get/set and chat stats I think), so, you need to have redis-server installed and running.
In ubuntu:

```
sudo apt-get install redis-server
redis-server 
```

If you want to know how to execute at start or something more about the install: http://redis.io/topics/quickstart

I`ve been thinking that maybe some users don't want to have redis executing, and have the ability that the plugins, if redis is nil, execute as always, but that can lead to redundant code if it's not structured properly.

**Comment by Sethlans** [comment]
Thanks for explaining. now i have installed redis and all works now

**Comment by P0L4C0** [comment]
Hi, I installed redis but I get the following when starting the bot: 

    $ ./launch.sh
    Telegram-cli version 1.1.1, Copyright (C) 2013-2014 Vitaly Valtman
    Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
    This is free software, and you are welcome to redistribute it
    under certain conditions; type `show_license' for details.
    I: config dir=[/home/fabio/.telegram-cli]
     *** lua: ./libs/redis.lua:1: module 'redis' not found:
    	no field package.preload['redis']
    	no file '/usr/local/share/lua/5.2/redis.lua'
    	no file '/usr/local/share/lua/5.2/redis/init.lua'
    	no file '/usr/local/lib/lua/5.2/redis.lua'
    	no file '/usr/local/lib/lua/5.2/redis/init.lua'
    	no file '/usr/share/lua/5.2/redis.lua'
    	no file '/usr/share/lua/5.2/redis/init.lua'
    	no file './redis.lua'
    	no file '.luarocks/share/lua/5.2/redis.lua'
    	no file '.luarocks/share/lua/5.2/redis/init.lua'
    	no file '/usr/local/lib/lua/5.2/redis.so'
    	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/redis.so'
    	no file '/usr/lib/lua/5.2/redis.so'
    	no file '/usr/local/lib/lua/5.2/loadall.so'
    	no file './redis.so'
    	no file '.luarocks/lib/lua/5.2/redis.so'

Am I missing something?

Thanks!

**Comment by rockneurotiko** [comment]
@P0L4C0 How did you execute it?
If you've made a clean download, you have to do './launch install' before.
If your telegram-bot is older than redis patches, you have to do './launch update'

After that, if still don't, probable you have some problems with the lua versions, for example, my SO (arch linux) install the libraries of luarocks with the 5.1 version, but execute with 5.2.

**Comment by yagop** [comment]
> I`ve been thinking that maybe some users don't want to have redis executing, and have the ability that the plugins, if redis is nil, execute as always, but that can lead to redundant code if it's not structured properly.

That was the idea at first, but takes more time than I thought. I think best way is to overwrite redis functions.

@P0L4C0 as @rockneurotiko said:

> If you've made a clean download, you have to do `./launch install` before.
> If your telegram-bot is older than redis patches, you have to do `./launch update`

**Comment by yagop** [comment]
I added [fakeredis](https://github.com/catwell/fakeredis) for those pleasants who doesn't want to install Redis.

## Warning
__There isn't any data persistance (data will be lost after bot reset).
[Some](https://github.com/catwell/fakeredis/blob/master/supported.txt) functions won't work.__

PS: Redis is awesome and you should being trying it now. :grinning:

**Comment by rockneurotiko** [comment]
@yagop fakeredis is ok when you want that your app don't crash, but won't save nothing, and you can't know if you are in fakeredis or in redis.

For example, I have a plugin (that I will probably clean up and PR) that let you have redis or not (I have the bot running in a limited machine, and although I love redis I can't have it running). 
This is the code that get and save in local or redis:

``` lua
local function get_from_db(id)
   if redis == nil then
      return _lists[id]
   else
      local base = get_base_redis()
      return redis:hget(base, id)
   end
end

local function save_in_db(value, id)
   if redis == nil then
      _lists[id] = value
      serialize_to_file(_lists, _file_list)
   else
      local base = get_base_redis()
      redis:hset(base, id, value)
   end
end
```

Right now, with my solution, I can't update the bot, because will never know if a redis server is running or not, if is running all ok, if it's not running, it will use the fake but won't save anything, and I don't have any way to know if it's fakeredis (with my limited lua knowdledge).

I would be happy if you put a flag to know if is using redis or fakeredis, with that I can use redis (fake or normal) and if it's fake, save it in disk when needed.

I don't know if I've explained well.. my english is not so good..

**Comment by yagop** [comment]
I will add a flag or a property on the redis table, but there is a workaround: 

There are functions on fakeredis returns `nil` but on redis returns an array or a string.
Try `redis:info()`. I havent tested it but should works.

**Comment by yagop** [comment]
Flag `redis.fakeredis` added. 

b172f186ee468e7c43ed

**Comment by rockneurotiko** [comment]
Thanks for the flag!

I guess that we can close this issue :)
