### ISSUE TITLE
tweet plugin

### ISSUE THREAD

**Issue by anvaruk** [yagop/telegram-bot#173]
for some reason it does not send a tweet from specified username, but instead sends my own tweets

e.g !tweet id BarackObama
will return tweets from my account instead

It also will look much better if bot returns just the url of the tweet
telegram then generates preview itself

**Comment by rockneurotiko** [comment]
The reason is because the id is the account id, for barack obama is 813286:

![captura de pantalla de 2015-05-20 13 07 58](https://cloud.githubusercontent.com/assets/1377584/7724360/4d2b29d2-fef1-11e4-82d2-87f50c019864.png)

I should restrict the ID to numbers and check if the ID received is the same.

If you want a name should be:
!tweet name barackobama

![captura de pantalla de 2015-05-20 13 09 43](https://cloud.githubusercontent.com/assets/1377584/7724395/8237a380-fef1-11e4-906a-aece8ac97f82.png)

The reason that I don't return only the URL is because some clients don't generate the preview, and, if the tweet have a gif (mp4 for twitter), the preview don't show it, but the plugin send it ;-)

Also, if the tweet have an URL, the preview don't show you, but because the plugin send the text, it will preview the URL, much better! :smile:

**Comment by rockneurotiko** [comment]
Fixed that id let write a word and return an error in 0bb7567523706e8ddb78cf8cf836599814405d19 and 94e11ebb3017051c48d410c04714c1a7e3803dd5

![captura de pantalla de 2015-05-20 13 30 28](https://cloud.githubusercontent.com/assets/1377584/7724716/685be068-fef4-11e4-9200-50cb4299bf9f.png)
![captura de pantalla de 2015-05-20 13 30 20](https://cloud.githubusercontent.com/assets/1377584/7724715/6857b718-fef4-11e4-8a20-812400e2e356.png)

**Comment by anvaruk** [comment]
I knew I'm doing something wrong
thanks!
